# See full list of defaults here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# To see all cops used see here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'build/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
  DisplayStyleGuide: true
  DisplayCopNames: true
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*jbuilder'
    - 'spec/**/*spec.rb'
    - 'app/serializers/*_serializer.rb'
  Max: 35

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousOperator:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'spec/**/*'

Layout/AlignParameters:
  Enabled: true

Layout/CaseIndentation:
  IndentOneStep: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Naming/PredicateName:
  NamePrefix:
    - is_
  NamePrefixBlacklist:
    - is_

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - 'app/views/**/*.jbuilder'

Style/RegexpLiteral:
  Exclude:
    - 'spec/**/*'

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  Enabled: false

Rails/FindEach:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/**/*'
