# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  facebook_app_id: 1582405371991209
  facebook_app_secret: 74d78499f732fcd93e4bdcb2e75d52e4
  secret_key_base: be2aa761c8d9f4af841cde72d9e5e574ed4a43b5e02ade136ad0ba22c794ea54ffe40893e9bdfb081b20f98964162275e5fdca6bf1badc05d62e11b0cc9a5b21

test:
  secret_key_base: 7a6ad89c0e0cd7cad32d5b3b5fef74009ce76306cc501ec8eba84dcfddac7a3298290940efa308684929d216f4653cec8e99761470fb07e0e4a72a35de22eae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
